# Gustavo Sanchez PSID:1861118

# input players jersey and rating
print("Enter player 1's jersey number:")
player1_jersey = int(input())
print("Enter player 1's rating:")
player1_rating = int(input())
print("\nEnter player 2's jersey number:")
player2_jersey = int(input())
print("Enter player 2's rating:")
player2_rating = int(input())
print("\nEnter player 3's jersey number:")
player3_jersey = int(input())
print("Enter player 3's rating:")
player3_rating = int(input())
print("\nEnter player 4's jersey number:")
player4_jersey = int(input())
print("Enter player 4's rating:")
player4_rating = int(input())
print("\nEnter player 5's jersey number:")
player5_jersey = int(input())
print("Enter player 5's rating:")
player5_rating = int(input())